server:
  port: 9527


spring:
  application:
    name: cloud-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: #配置路由方法一
        - id: payment_routh
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/hi/**

        - id: payment_routh2   #路由id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
#          filters:
#            -AddRequestParameter=X-Request-Id,1024
          predicates:
             - Path=/get/**   #断言，路径相匹配的进行路由
             - After=2020-06-19T15:20:02.131+08:00[Asia/Shanghai]  #在这个时间之后

eureka:
  client:
    register-with-eureka: true #向注册中心注册
    fetch-registry: true #从中心抓取已有的注册信息，默认true，单点无所谓，集群必须设置为true才能配合ribbon使用负载均匀
    service-url:
      #   defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway9527   #配置名称
    prefer-ip-address: true   #访问路径可以显示ip地址
